name: Publish NuGet

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.11

      - name: Restore
        run: dotnet restore src/Dot.Raft

      - name: Build
        run: dotnet build src/Dot.Raft -c Release --no-restore

      - name: Pack
        run: dotnet pack src/Dot.Raft -c Release -o out /p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }}

      - name: Publish to NuGet
        uses: actions/upload-artifact@v4
        with:
          name: NuGetPackage
          path: out/*.nupkg

      - name: Push to NuGet
        run: dotnet nuget push "out/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
        if: startsWith(github.ref, 'refs/tags/')
