name: Publish NuGet

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.11
        
      - name: Build Dot.Raft
        run: dotnet build src/Dot.Raft -c Release -p:Version=${{ env.GitVersion_SemVer }} -p:FileVersion=${{ env.GitVersion_AssemblySemVer }} -p:InformationalVersion=${{ env.GitVersion_InformationalVersion }}
          
      - name: Pack Dot.Raft
        run: dotnet pack src/Dot.Raft -c Release -p:Version=${{ env.GitVersion_FullSemVer }} --output ${{ github.workspace }}
        
      - name: Publish to NuGet
        uses: actions/upload-artifact@v4
        with:
          name: NuGetPackage
          path: out/*.nupkg
      
      - name: Push nuget
        run: dotnet nuget push ${{github.workspace}}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY  }}
        
